############
# Settings #
############
image: docker:24.0.6
services:
  - docker:24.0.6-dind
stages:
  - template
  - run
variables:
  KASM_RELEASE: "1.14.0"
  TEST_INSTALLER: "https://kasm-static-content.s3.amazonaws.com/kasm_release_1.14.0.7f3582.tar.gz"
before_script:
  - export SANITIZED_BRANCH="$(echo $CI_COMMIT_REF_NAME | sed -r 's#^release/##' | sed 's/\//_/g')"

#######################
# Build from template #
#######################
template:
  stage: template
  script:
    - apk add py3-jinja2 py3-yaml
    - cd ci-scripts
    - python3 template-gitlab.py
  tags:
    - oci-fixed-amd
  artifacts:
    paths:
      - gitlab-ci.yml
pipeline:
  stage: run
  trigger:
    include:
      - artifact: gitlab-ci.yml
        job: template
